---
- hosts: localhost
  become: true
  # become_method: su
  gather_facts: no
  # connection: local

  tasks:
  - set_fact:
      BUILD_ID:"{{ lookup('env','BUILD_ID') }}"
      DOCKER_USER="{{ lookup('env','DOCKER_USER') }}"
  - name: Build New Docker Image
    docker_image:
      path: ../tomcat
      name: "{{ DOCKER_USER }}/tomcat"
      tag: "pipeline-{{ BUILD_ID }}"
    register: docker_build
  - debug:
      msg: "Docker Image Build Done: {{ DOCKER_USER }}/tomcat:pipeline-{{ BUILD_ID }}"
